expansion:
  uspto:
    - C:\Users\alexander.korolyov\PycharmProjects\aizynth\config\uspto_model.onnx
    - C:\Users\alexander.korolyov\PycharmProjects\aizynth\config\uspto_templates.csv.gz
  ringbreaker:
    - C:\Users\alexander.korolyov\PycharmProjects\aizynth\config\uspto_ringbreaker_model.onnx
    - C:\Users\alexander.korolyov\PycharmProjects\aizynth\config\uspto_ringbreaker_templates.csv.gz
filter:
  uspto: C:\Users\alexander.korolyov\PycharmProjects\aizynth\config\uspto_filter_model.onnx
stock:
#  zinc: C:\Users\alexander.korolyov\PycharmProjects\aizynth\config\zinc_stock.hdf5
  molport_3d: C:\Users\alexander.korolyov\PycharmProjects\aizynth\config\molport_3d_stock.hdf5
  molport_5d: C:\Users\alexander.korolyov\PycharmProjects\aizynth\config\molport_5d_stock.hdf5
  molport_7d: C:\Users\alexander.korolyov\PycharmProjects\aizynth\config\molport_7d_stock.hdf5
search:
  time_limit: 900
  iteration_limit: 5000
  max_transforms: 6
  return_first: False
post_processing:
    min_routes: 1
    max_routes: 5
